# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.date_time_field import DateTimeField

class TestDateTimeField(unittest.TestCase):
    """DateTimeField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateTimeField:
        """Test DateTimeField
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateTimeField`
        """
        model = DateTimeField()
        if include_optional:
            return DateTimeField(
                name = '',
                type = openapi_client.models.date_time_field_type.DateTimeFieldType(
                    name = '', 
                    duration_type = openapi_client.models.duration_field_type.DurationFieldType(
                        name = '', ), 
                    range_duration_type = openapi_client.models.duration_field_type.DurationFieldType(
                        name = '', ), ),
                supported = True,
                lenient = True,
                minimum_value = 56,
                maximum_value = 56,
                duration_field = openapi_client.models.duration_field.DurationField(
                    name = '', 
                    type = openapi_client.models.duration_field_type.DurationFieldType(
                        name = '', ), 
                    supported = True, 
                    unit_millis = 56, 
                    precise = True, ),
                range_duration_field = openapi_client.models.duration_field.DurationField(
                    name = '', 
                    type = openapi_client.models.duration_field_type.DurationFieldType(
                        name = '', ), 
                    supported = True, 
                    unit_millis = 56, 
                    precise = True, ),
                leap_duration_field = openapi_client.models.duration_field.DurationField(
                    name = '', 
                    type = openapi_client.models.duration_field_type.DurationFieldType(
                        name = '', ), 
                    supported = True, 
                    unit_millis = 56, 
                    precise = True, )
            )
        else:
            return DateTimeField(
        )
        """

    def testDateTimeField(self):
        """Test DateTimeField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
