# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.products_inner1_total_price_breakdown_inner import ProductsInner1TotalPriceBreakdownInner

class TestProductsInner1TotalPriceBreakdownInner(unittest.TestCase):
    """ProductsInner1TotalPriceBreakdownInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductsInner1TotalPriceBreakdownInner:
        """Test ProductsInner1TotalPriceBreakdownInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductsInner1TotalPriceBreakdownInner`
        """
        model = ProductsInner1TotalPriceBreakdownInner()
        if include_optional:
            return ProductsInner1TotalPriceBreakdownInner(
                currency_type = 'BILLC',
                price_currency = 'GBP',
                price_breakdown = [
                    openapi_client.models.products_inner_1_total_price_breakdown_inner_price_breakdown_inner.products_inner_1_totalPriceBreakdown_inner_priceBreakdown_inner(
                        type_code = 'SPRQT', 
                        price = 114.92, )
                    ]
            )
        else:
            return ProductsInner1TotalPriceBreakdownInner(
        )
        """

    def testProductsInner1TotalPriceBreakdownInner(self):
        """Test ProductsInner1TotalPriceBreakdownInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
