# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.supermodel_io_logistics_express_landed_cost_request import SupermodelIoLogisticsExpressLandedCostRequest

class TestSupermodelIoLogisticsExpressLandedCostRequest(unittest.TestCase):
    """SupermodelIoLogisticsExpressLandedCostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupermodelIoLogisticsExpressLandedCostRequest:
        """Test SupermodelIoLogisticsExpressLandedCostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupermodelIoLogisticsExpressLandedCostRequest`
        """
        model = SupermodelIoLogisticsExpressLandedCostRequest()
        if include_optional:
            return SupermodelIoLogisticsExpressLandedCostRequest(
                customer_details = openapi_client.models.supermodel_io_logistics_express_landed_cost_request_customer_details.supermodelIoLogisticsExpressLandedCostRequest_customerDetails(
                    shipper_details = openapi_client.models.address_definition_for_/rates,_/products,_/landed_cost.Address definition for /rates, /products, /landed-cost(
                        postal_code = '14800', 
                        city_name = 'Prague', 
                        country_code = 'CZ', 
                        province_code = 'CZ', 
                        address_line1 = 'addres1', 
                        address_line2 = 'addres2', 
                        address_line3 = 'addres3', 
                        county_name = 'Central Bohemia', ), 
                    receiver_details = openapi_client.models.address_definition_for_/rates,_/products,_/landed_cost.Address definition for /rates, /products, /landed-cost(
                        postal_code = '14800', 
                        city_name = 'Prague', 
                        country_code = 'CZ', 
                        province_code = 'CZ', 
                        address_line1 = 'addres1', 
                        address_line2 = 'addres2', 
                        address_line3 = 'addres3', 
                        county_name = 'Central Bohemia', ), ),
                accounts = [
                    openapi_client.models.account_definition.Account definition(
                        type_code = 'shipper', 
                        number = '123456789', )
                    ],
                product_code = 'P',
                local_product_code = 'P',
                unit_of_measurement = 'metric',
                currency_code = 'CZK',
                is_customs_declarable = True,
                is_dtp_requested = True,
                is_insurance_requested = False,
                get_cost_breakdown = True,
                charges = [
                    openapi_client.models.supermodel_io_logistics_express_landed_cost_request_charges_inner.supermodelIoLogisticsExpressLandedCostRequest_charges_inner(
                        type_code = 'insurance', 
                        amount = 1250, 
                        currency_code = 'CZK', )
                    ],
                shipment_purpose = 'personal',
                transportation_mode = 'air',
                merchant_selected_carrier_name = 'DHL',
                packages = [
                    openapi_client.models.package_definition_for_/rates,_/products,_/landed_cost.Package definition for /rates, /products, /landed-cost(
                        type_code = '3BX', 
                        weight = 10.5, 
                        dimensions = openapi_client.models.dimensions.dimensions(
                            length = 25, 
                            width = 35, 
                            height = 15, ), )
                    ],
                items = [
                    openapi_client.models.supermodel_io_logistics_express_landed_cost_request_items_inner.supermodelIoLogisticsExpressLandedCostRequest_items_inner(
                        number = 1, 
                        name = 'KNITWEAR COTTON', 
                        description = 'KNITWEAR 100% COTTON REDUCTION PRICE FALL COLLECTION', 
                        manufacturer_country = 'CN', 
                        part_number = '12345555', 
                        quantity = 2, 
                        quantity_type = 'prt', 
                        unit_price = 120, 
                        unit_price_currency_code = 'EUR', 
                        customs_value = 120, 
                        customs_value_currency_code = 'EUR', 
                        commodity_code = '851713', 
                        weight = 5, 
                        weight_unit_of_measurement = 'metric', 
                        category = '204', 
                        brand = 'SHOE 1', 
                        goods_characteristics = [
                            openapi_client.models.supermodel_io_logistics_express_landed_cost_request_items_inner_goods_characteristics_inner.supermodelIoLogisticsExpressLandedCostRequest_items_inner_goodsCharacteristics_inner(
                                type_code = 'IMPORTER', 
                                value = 'Registered', )
                            ], 
                        additional_quantity_definitions = [
                            openapi_client.models.supermodel_io_logistics_express_landed_cost_request_items_inner_additional_quantity_definitions_inner.supermodelIoLogisticsExpressLandedCostRequest_items_inner_additionalQuantityDefinitions_inner(
                                type_code = 'DPR', 
                                amount = 2, )
                            ], 
                        estimated_tariff_rate_type = 'default_rate', )
                    ],
                get_tariff_formula = True,
                get_quotation_id = True
            )
        else:
            return SupermodelIoLogisticsExpressLandedCostRequest(
                customer_details = openapi_client.models.supermodel_io_logistics_express_landed_cost_request_customer_details.supermodelIoLogisticsExpressLandedCostRequest_customerDetails(
                    shipper_details = openapi_client.models.address_definition_for_/rates,_/products,_/landed_cost.Address definition for /rates, /products, /landed-cost(
                        postal_code = '14800', 
                        city_name = 'Prague', 
                        country_code = 'CZ', 
                        province_code = 'CZ', 
                        address_line1 = 'addres1', 
                        address_line2 = 'addres2', 
                        address_line3 = 'addres3', 
                        county_name = 'Central Bohemia', ), 
                    receiver_details = openapi_client.models.address_definition_for_/rates,_/products,_/landed_cost.Address definition for /rates, /products, /landed-cost(
                        postal_code = '14800', 
                        city_name = 'Prague', 
                        country_code = 'CZ', 
                        province_code = 'CZ', 
                        address_line1 = 'addres1', 
                        address_line2 = 'addres2', 
                        address_line3 = 'addres3', 
                        county_name = 'Central Bohemia', ), ),
                accounts = [
                    openapi_client.models.account_definition.Account definition(
                        type_code = 'shipper', 
                        number = '123456789', )
                    ],
                unit_of_measurement = 'metric',
                currency_code = 'CZK',
                is_customs_declarable = True,
                get_cost_breakdown = True,
                packages = [
                    openapi_client.models.package_definition_for_/rates,_/products,_/landed_cost.Package definition for /rates, /products, /landed-cost(
                        type_code = '3BX', 
                        weight = 10.5, 
                        dimensions = openapi_client.models.dimensions.dimensions(
                            length = 25, 
                            width = 35, 
                            height = 15, ), )
                    ],
                items = [
                    openapi_client.models.supermodel_io_logistics_express_landed_cost_request_items_inner.supermodelIoLogisticsExpressLandedCostRequest_items_inner(
                        number = 1, 
                        name = 'KNITWEAR COTTON', 
                        description = 'KNITWEAR 100% COTTON REDUCTION PRICE FALL COLLECTION', 
                        manufacturer_country = 'CN', 
                        part_number = '12345555', 
                        quantity = 2, 
                        quantity_type = 'prt', 
                        unit_price = 120, 
                        unit_price_currency_code = 'EUR', 
                        customs_value = 120, 
                        customs_value_currency_code = 'EUR', 
                        commodity_code = '851713', 
                        weight = 5, 
                        weight_unit_of_measurement = 'metric', 
                        category = '204', 
                        brand = 'SHOE 1', 
                        goods_characteristics = [
                            openapi_client.models.supermodel_io_logistics_express_landed_cost_request_items_inner_goods_characteristics_inner.supermodelIoLogisticsExpressLandedCostRequest_items_inner_goodsCharacteristics_inner(
                                type_code = 'IMPORTER', 
                                value = 'Registered', )
                            ], 
                        additional_quantity_definitions = [
                            openapi_client.models.supermodel_io_logistics_express_landed_cost_request_items_inner_additional_quantity_definitions_inner.supermodelIoLogisticsExpressLandedCostRequest_items_inner_additionalQuantityDefinitions_inner(
                                type_code = 'DPR', 
                                amount = 2, )
                            ], 
                        estimated_tariff_rate_type = 'default_rate', )
                    ],
        )
        """

    def testSupermodelIoLogisticsExpressLandedCostRequest(self):
        """Test SupermodelIoLogisticsExpressLandedCostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
