# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.products_inner1_detailed_price_breakdown_inner_breakdown_inner import ProductsInner1DetailedPriceBreakdownInnerBreakdownInner

class TestProductsInner1DetailedPriceBreakdownInnerBreakdownInner(unittest.TestCase):
    """ProductsInner1DetailedPriceBreakdownInnerBreakdownInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductsInner1DetailedPriceBreakdownInnerBreakdownInner:
        """Test ProductsInner1DetailedPriceBreakdownInnerBreakdownInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductsInner1DetailedPriceBreakdownInnerBreakdownInner`
        """
        model = ProductsInner1DetailedPriceBreakdownInnerBreakdownInner()
        if include_optional:
            return ProductsInner1DetailedPriceBreakdownInnerBreakdownInner(
                name = '12:00 PREMIUM',
                service_code = 'YK',
                local_service_code = 'YK',
                type_code = '',
                service_type_code = 'SCH',
                price = 5,
                price_currency = 'GBP',
                is_customer_agreement = False,
                is_marketed_service = False,
                is_billing_service_indicator = False,
                price_breakdown = [
                    openapi_client.models.price_detail_inner.priceDetail_inner(
                        price_type = 'TAX', 
                        type_code = 'All Bu', 
                        price = 0, 
                        rate = 0, 
                        base_price = 5, )
                    ],
                tariff_rate_formula = '((0.3464 % COST) MAX (528.33))'
            )
        else:
            return ProductsInner1DetailedPriceBreakdownInnerBreakdownInner(
        )
        """

    def testProductsInner1DetailedPriceBreakdownInnerBreakdownInner(self):
        """Test ProductsInner1DetailedPriceBreakdownInnerBreakdownInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
