# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.supermodel_io_logistics_express_rates import SupermodelIoLogisticsExpressRates

class TestSupermodelIoLogisticsExpressRates(unittest.TestCase):
    """SupermodelIoLogisticsExpressRates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupermodelIoLogisticsExpressRates:
        """Test SupermodelIoLogisticsExpressRates
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupermodelIoLogisticsExpressRates`
        """
        model = SupermodelIoLogisticsExpressRates()
        if include_optional:
            return SupermodelIoLogisticsExpressRates(
                products = [
                    openapi_client.models.products_inner_1.products_inner_1(
                        product_name = 'EXPRESS DOMESTIC', 
                        product_code = 'N', 
                        local_product_code = 'N', 
                        local_product_country_code = 'CZ', 
                        network_type_code = 'TD', 
                        is_customer_agreement = False, 
                        weight = openapi_client.models.weight.weight(
                            volumetric = 0, 
                            provided = 1.5, 
                            unit_of_measurement = 'metric', ), 
                        total_price = [
                            openapi_client.models.products_inner_1_total_price_inner.products_inner_1_totalPrice_inner(
                                currency_type = 'BILLC', 
                                price_currency = 'GBP', 
                                price = 141.51, )
                            ], 
                        total_price_breakdown = [
                            openapi_client.models.products_inner_1_total_price_breakdown_inner.products_inner_1_totalPriceBreakdown_inner(
                                currency_type = 'BILLC', 
                                price_currency = 'GBP', 
                                price_breakdown = [
                                    openapi_client.models.products_inner_1_total_price_breakdown_inner_price_breakdown_inner.products_inner_1_totalPriceBreakdown_inner_priceBreakdown_inner(
                                        type_code = 'SPRQT', 
                                        price = 114.92, )
                                    ], )
                            ], 
                        detailed_price_breakdown = [
                            openapi_client.models.products_inner_1_detailed_price_breakdown_inner.products_inner_1_detailedPriceBreakdown_inner(
                                currency_type = 'BILLC', 
                                price_currency = 'GBP', 
                                breakdown = [
                                    openapi_client.models.products_inner_1_detailed_price_breakdown_inner_breakdown_inner.products_inner_1_detailedPriceBreakdown_inner_breakdown_inner(
                                        name = '12:00 PREMIUM', 
                                        service_code = 'YK', 
                                        local_service_code = 'YK', 
                                        type_code = '', 
                                        service_type_code = 'SCH', 
                                        price = 5, 
                                        price_currency = 'GBP', 
                                        is_customer_agreement = False, 
                                        is_marketed_service = False, 
                                        is_billing_service_indicator = False, 
                                        tariff_rate_formula = '((0.3464 % COST) MAX (528.33))', )
                                    ], )
                            ], 
                        service_code_mutually_exclusive_groups = [
                            openapi_client.models.products_inner_service_code_mutually_exclusive_groups_inner.products_inner_serviceCodeMutuallyExclusiveGroups_inner(
                                service_code_rule_name = 'Exclusive Billing Services', 
                                description = 'Mutually exclusive Billing Services - shipment can contain just one of following', 
                                service_codes = [
                                    openapi_client.models.products_inner_service_code_mutually_exclusive_groups_inner_service_codes_inner.products_inner_serviceCodeMutuallyExclusiveGroups_inner_serviceCodes_inner(
                                        service_code = 'PZ', )
                                    ], )
                            ], 
                        service_code_dependency_rule_groups = [
                            openapi_client.models.products_inner_service_code_dependency_rule_groups_inner.products_inner_serviceCodeDependencyRuleGroups_inner(
                                dependent_service_code = 'PZ', 
                                dependency_rule_group = [
                                    openapi_client.models.products_inner_service_code_dependency_rule_groups_inner_dependency_rule_group_inner.products_inner_serviceCodeDependencyRuleGroups_inner_dependencyRuleGroup_inner(
                                        dependency_rule_name = 'Labelfree and PLT rule', 
                                        dependency_description = 'Labelfree requires Paperless Trade (PLT) only if PLT is allowed for product globaly', 
                                        dependency_condition = 'Must provide the requiredServiceCode if it is allowed for the productCode', 
                                        required_service_codes = [
                                            openapi_client.models.products_inner_service_code_dependency_rule_groups_inner_dependency_rule_group_inner_required_service_codes_inner.products_inner_serviceCodeDependencyRuleGroups_inner_dependencyRuleGroup_inner_requiredServiceCodes_inner(
                                                service_code = 'WY', )
                                            ], )
                                    ], )
                            ], 
                        pickup_capabilities = openapi_client.models.products_inner_1_pickup_capabilities.products_inner_1_pickupCapabilities(
                            next_business_day = False, 
                            local_cutoff_date_and_time = '2019-09-18T15:00:00', 
                            gmt_cutoff_time = '16:00:00', 
                            pickup_earliest = '09:30:00', 
                            pickup_latest = '16:00:00', 
                            origin_service_area_code = 'ELA', 
                            origin_facility_area_code = 'HHR', 
                            pickup_additional_days = 0, 
                            pickup_day_of_week = 3, ), 
                        delivery_capabilities = openapi_client.models.products_inner_1_delivery_capabilities.products_inner_1_deliveryCapabilities(
                            delivery_type_code = 'QDDC', 
                            estimated_delivery_date_and_time = '2019-09-20T12:00:00', 
                            destination_service_area_code = 'PRG', 
                            destination_facility_area_code = 'PR3', 
                            delivery_additional_days = 0, 
                            delivery_day_of_week = 5, 
                            total_transit_days = 2, ), 
                        items = [
                            None
                            ], 
                        pricing_date = '2020-02-25', )
                    ],
                exchange_rates = [
                    openapi_client.models.exchange_rates_inner.exchangeRates_inner(
                        current_exchange_rate = 1.188411, 
                        currency = 'GBP', 
                        base_currency = 'EUR', )
                    ],
                warnings = [
                    'Price can't be calculated'
                    ]
            )
        else:
            return SupermodelIoLogisticsExpressRates(
                products = [
                    openapi_client.models.products_inner_1.products_inner_1(
                        product_name = 'EXPRESS DOMESTIC', 
                        product_code = 'N', 
                        local_product_code = 'N', 
                        local_product_country_code = 'CZ', 
                        network_type_code = 'TD', 
                        is_customer_agreement = False, 
                        weight = openapi_client.models.weight.weight(
                            volumetric = 0, 
                            provided = 1.5, 
                            unit_of_measurement = 'metric', ), 
                        total_price = [
                            openapi_client.models.products_inner_1_total_price_inner.products_inner_1_totalPrice_inner(
                                currency_type = 'BILLC', 
                                price_currency = 'GBP', 
                                price = 141.51, )
                            ], 
                        total_price_breakdown = [
                            openapi_client.models.products_inner_1_total_price_breakdown_inner.products_inner_1_totalPriceBreakdown_inner(
                                currency_type = 'BILLC', 
                                price_currency = 'GBP', 
                                price_breakdown = [
                                    openapi_client.models.products_inner_1_total_price_breakdown_inner_price_breakdown_inner.products_inner_1_totalPriceBreakdown_inner_priceBreakdown_inner(
                                        type_code = 'SPRQT', 
                                        price = 114.92, )
                                    ], )
                            ], 
                        detailed_price_breakdown = [
                            openapi_client.models.products_inner_1_detailed_price_breakdown_inner.products_inner_1_detailedPriceBreakdown_inner(
                                currency_type = 'BILLC', 
                                price_currency = 'GBP', 
                                breakdown = [
                                    openapi_client.models.products_inner_1_detailed_price_breakdown_inner_breakdown_inner.products_inner_1_detailedPriceBreakdown_inner_breakdown_inner(
                                        name = '12:00 PREMIUM', 
                                        service_code = 'YK', 
                                        local_service_code = 'YK', 
                                        type_code = '', 
                                        service_type_code = 'SCH', 
                                        price = 5, 
                                        price_currency = 'GBP', 
                                        is_customer_agreement = False, 
                                        is_marketed_service = False, 
                                        is_billing_service_indicator = False, 
                                        tariff_rate_formula = '((0.3464 % COST) MAX (528.33))', )
                                    ], )
                            ], 
                        service_code_mutually_exclusive_groups = [
                            openapi_client.models.products_inner_service_code_mutually_exclusive_groups_inner.products_inner_serviceCodeMutuallyExclusiveGroups_inner(
                                service_code_rule_name = 'Exclusive Billing Services', 
                                description = 'Mutually exclusive Billing Services - shipment can contain just one of following', 
                                service_codes = [
                                    openapi_client.models.products_inner_service_code_mutually_exclusive_groups_inner_service_codes_inner.products_inner_serviceCodeMutuallyExclusiveGroups_inner_serviceCodes_inner(
                                        service_code = 'PZ', )
                                    ], )
                            ], 
                        service_code_dependency_rule_groups = [
                            openapi_client.models.products_inner_service_code_dependency_rule_groups_inner.products_inner_serviceCodeDependencyRuleGroups_inner(
                                dependent_service_code = 'PZ', 
                                dependency_rule_group = [
                                    openapi_client.models.products_inner_service_code_dependency_rule_groups_inner_dependency_rule_group_inner.products_inner_serviceCodeDependencyRuleGroups_inner_dependencyRuleGroup_inner(
                                        dependency_rule_name = 'Labelfree and PLT rule', 
                                        dependency_description = 'Labelfree requires Paperless Trade (PLT) only if PLT is allowed for product globaly', 
                                        dependency_condition = 'Must provide the requiredServiceCode if it is allowed for the productCode', 
                                        required_service_codes = [
                                            openapi_client.models.products_inner_service_code_dependency_rule_groups_inner_dependency_rule_group_inner_required_service_codes_inner.products_inner_serviceCodeDependencyRuleGroups_inner_dependencyRuleGroup_inner_requiredServiceCodes_inner(
                                                service_code = 'WY', )
                                            ], )
                                    ], )
                            ], 
                        pickup_capabilities = openapi_client.models.products_inner_1_pickup_capabilities.products_inner_1_pickupCapabilities(
                            next_business_day = False, 
                            local_cutoff_date_and_time = '2019-09-18T15:00:00', 
                            gmt_cutoff_time = '16:00:00', 
                            pickup_earliest = '09:30:00', 
                            pickup_latest = '16:00:00', 
                            origin_service_area_code = 'ELA', 
                            origin_facility_area_code = 'HHR', 
                            pickup_additional_days = 0, 
                            pickup_day_of_week = 3, ), 
                        delivery_capabilities = openapi_client.models.products_inner_1_delivery_capabilities.products_inner_1_deliveryCapabilities(
                            delivery_type_code = 'QDDC', 
                            estimated_delivery_date_and_time = '2019-09-20T12:00:00', 
                            destination_service_area_code = 'PRG', 
                            destination_facility_area_code = 'PR3', 
                            delivery_additional_days = 0, 
                            delivery_day_of_week = 5, 
                            total_transit_days = 2, ), 
                        items = [
                            None
                            ], 
                        pricing_date = '2020-02-25', )
                    ],
        )
        """

    def testSupermodelIoLogisticsExpressRates(self):
        """Test SupermodelIoLogisticsExpressRates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
