# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.supermodel_io_logistics_express_delivery_options_response import SupermodelIoLogisticsExpressDeliveryOptionsResponse

class TestSupermodelIoLogisticsExpressDeliveryOptionsResponse(unittest.TestCase):
    """SupermodelIoLogisticsExpressDeliveryOptionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupermodelIoLogisticsExpressDeliveryOptionsResponse:
        """Test SupermodelIoLogisticsExpressDeliveryOptionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupermodelIoLogisticsExpressDeliveryOptionsResponse`
        """
        model = SupermodelIoLogisticsExpressDeliveryOptionsResponse()
        if include_optional:
            return SupermodelIoLogisticsExpressDeliveryOptionsResponse(
                delivery_options = [
                    openapi_client.models.supermodel_io_logistics_express_delivery_options_response_delivery_options_inner.supermodelIoLogisticsExpressDeliveryOptionsResponse_deliveryOptions_inner(
                        type = 'signatureRelease', 
                        parameters = [
                            openapi_client.models.supermodel_io_logistics_express_delivery_options_response_delivery_options_inner_parameters_inner.supermodelIoLogisticsExpressDeliveryOptionsResponse_deliveryOptions_inner_parameters_inner(
                                name = 'authorizerName', 
                                is_required = True, 
                                accepted_values = [
                                    'Front door'
                                    ], )
                            ], 
                        service_point_url = 'https://expressapi.dhl.com/mydhlapi/servicepoints?servicePointResults=10&address=BEWDLEY%20DY12%201PY&countryCode=GB&capability=81,73,74,88&language=en', 
                        delivery_windows = [
                            openapi_client.models.supermodel_io_logistics_express_delivery_options_response_delivery_options_inner_delivery_windows_inner.supermodelIoLogisticsExpressDeliveryOptionsResponse_deliveryOptions_inner_deliveryWindows_inner(
                                start_date_time = '2023-08-23T17:00:00 GMT+01:00', 
                                end_date_time = '2023-08-23T21:00:00 GMT+01:00', )
                            ], )
                    ],
                warnings = [
                    ''
                    ]
            )
        else:
            return SupermodelIoLogisticsExpressDeliveryOptionsResponse(
                delivery_options = [
                    openapi_client.models.supermodel_io_logistics_express_delivery_options_response_delivery_options_inner.supermodelIoLogisticsExpressDeliveryOptionsResponse_deliveryOptions_inner(
                        type = 'signatureRelease', 
                        parameters = [
                            openapi_client.models.supermodel_io_logistics_express_delivery_options_response_delivery_options_inner_parameters_inner.supermodelIoLogisticsExpressDeliveryOptionsResponse_deliveryOptions_inner_parameters_inner(
                                name = 'authorizerName', 
                                is_required = True, 
                                accepted_values = [
                                    'Front door'
                                    ], )
                            ], 
                        service_point_url = 'https://expressapi.dhl.com/mydhlapi/servicepoints?servicePointResults=10&address=BEWDLEY%20DY12%201PY&countryCode=GB&capability=81,73,74,88&language=en', 
                        delivery_windows = [
                            openapi_client.models.supermodel_io_logistics_express_delivery_options_response_delivery_options_inner_delivery_windows_inner.supermodelIoLogisticsExpressDeliveryOptionsResponse_deliveryOptions_inner_deliveryWindows_inner(
                                start_date_time = '2023-08-23T17:00:00 GMT+01:00', 
                                end_date_time = '2023-08-23T21:00:00 GMT+01:00', )
                            ], )
                    ],
        )
        """

    def testSupermodelIoLogisticsExpressDeliveryOptionsResponse(self):
        """Test SupermodelIoLogisticsExpressDeliveryOptionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
