# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Suggestion(BaseModel):
    """
    Suggestion for the search address
    """ # noqa: E501
    label: Optional[StrictStr] = Field(default=None, description="Always holds null value")
    value: Optional[StrictStr] = Field(default=None, description="Always holds null value")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude of the geocoded search address (used for GREF web service search)")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude of the geocoded search address (used for GREF web service search)")
    country_code: Optional[StrictStr] = Field(default=None, description="Country code of the search address", alias="countryCode")
    place_id: Optional[StrictStr] = Field(default=None, description="Place id of the search address", alias="placeId")
    provider_id: Optional[StrictStr] = Field(default=None, description="Provider id of the search address", alias="providerId")
    __properties: ClassVar[List[str]] = ["label", "value", "latitude", "longitude", "countryCode", "placeId", "providerId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Suggestion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Suggestion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label": obj.get("label"),
            "value": obj.get("value"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "countryCode": obj.get("countryCode"),
            "placeId": obj.get("placeId"),
            "providerId": obj.get("providerId")
        })
        return _obj


