# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SupermodelIoLogisticsExpressAddressCreateShipmentResponse(BaseModel):
    """
    SupermodelIoLogisticsExpressAddressCreateShipmentResponse
    """ # noqa: E501
    postal_code: Annotated[str, Field(min_length=0, strict=True, max_length=12)] = Field(description="Postal code", alias="postalCode")
    city_name: Annotated[str, Field(min_length=1, strict=True, max_length=45)] = Field(description="City name", alias="cityName")
    country_code: Annotated[str, Field(min_length=2, strict=True, max_length=2)] = Field(description="Country code", alias="countryCode")
    province_code: Optional[StrictStr] = Field(default=None, description="Province or state code", alias="provinceCode")
    address_line1: Annotated[str, Field(min_length=1, strict=True, max_length=45)] = Field(description="Address line 1", alias="addressLine1")
    address_line2: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=45)]] = Field(default=None, description="Address line 2", alias="addressLine2")
    address_line3: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=45)]] = Field(default=None, description="Address line 3", alias="addressLine3")
    city_district_name: Optional[Annotated[str, Field(strict=True, max_length=45)]] = Field(default=None, description="Suburb or county name", alias="cityDistrictName")
    province_name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=35)]] = Field(default=None, description="Please enter your state or province name", alias="provinceName")
    country_name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=35)]] = Field(default=None, description="Please enter your country name", alias="countryName")
    __properties: ClassVar[List[str]] = ["postalCode", "cityName", "countryCode", "provinceCode", "addressLine1", "addressLine2", "addressLine3", "cityDistrictName", "provinceName", "countryName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SupermodelIoLogisticsExpressAddressCreateShipmentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SupermodelIoLogisticsExpressAddressCreateShipmentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "postalCode": obj.get("postalCode"),
            "cityName": obj.get("cityName"),
            "countryCode": obj.get("countryCode"),
            "provinceCode": obj.get("provinceCode"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "addressLine3": obj.get("addressLine3"),
            "cityDistrictName": obj.get("cityDistrictName"),
            "provinceName": obj.get("provinceName"),
            "countryName": obj.get("countryName")
        })
        return _obj


