# Generated by Django 5.0.6 on 2024-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_address", models.JSONField()),
                ("package_details", models.JSONField()),
                ("tracking_number", models.CharField(max_length=50)),
            ],
        ),
    ]
