# Generated by Django 4.2.9 on 2024-05-22 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="package_details",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="recipient_address",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="tracking_number",
        ),
        migrations.AddField(
            model_name="shipment",
            name="info",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="shipment",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
