# Generated by Django 4.2.9 on 2024-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_shipment_package_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="info",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="price",
        ),
        migrations.AddField(
            model_name="shipment",
            name="bypass_plt_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="message_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="message_reference_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="plugin_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="plugin_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_system_platform_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_system_platform_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="strict_validation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="validate_data_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="webstore_platform_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="webstore_platform_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
