# Generated by Django 4.2.9 on 2024-06-09 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_shipment_info_remove_shipment_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="bypass_plt_error",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="message_reference",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="message_reference_date",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="plugin_name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="plugin_version",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="shipping_system_platform_name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="shipping_system_platform_version",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="strict_validation",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="validate_data_only",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="webstore_platform_name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="webstore_platform_version",
        ),
        migrations.AddField(
            model_name="shipment",
            name="bill_to_account",
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="contents",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_airport_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="facility_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="licence_plate_no",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="outbound_mail_sort_code",
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="plt",
            field=models.BooleanField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="product_abbreviation",
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_address1",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_address2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_address3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_attention",
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_city",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_company_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_country",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_country_code",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_postcode",
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="receiver_telephone",
            field=models.CharField(default=43543645, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_declared_value",
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_id",
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_pieces",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_reference",
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_weight",
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_account_number",
            field=models.CharField(default=123, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_address1",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_address2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_address3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_airport_code",
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_city",
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_company_name",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_country",
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_name",
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_phone",
            field=models.CharField(default=123122, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_postcode",
            field=models.CharField(default=12312, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight_rounded",
            field=models.DecimalField(decimal_places=2, default=12312, max_digits=10),
            preserve_default=False,
        ),
    ]
