# coding: utf-8

"""
    DHL Express APIs (MyDHL API)

    Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services   In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 

    The version of the OpenAPI document: 2.11.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.supermodel_io_logistics_express_pickup_request import SupermodelIoLogisticsExpressPickupRequest
from openapi_client.models.supermodel_io_logistics_express_pickup_response import SupermodelIoLogisticsExpressPickupResponse
from openapi_client.models.supermodel_io_logistics_express_update_pickup_request import SupermodelIoLogisticsExpressUpdatePickupRequest
from openapi_client.models.supermodel_io_logistics_express_update_pickup_response import SupermodelIoLogisticsExpressUpdatePickupResponse

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class PickupApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def exp_api_pickups(
        self,
        supermodel_io_logistics_express_pickup_request: Annotated[SupermodelIoLogisticsExpressPickupRequest, Field(description="Details about the requested pickup")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SupermodelIoLogisticsExpressPickupResponse:
        """Create a DHL Express pickup booking request

        The Pickup service creates a DHL Express pickup booking request 

        :param supermodel_io_logistics_express_pickup_request: Details about the requested pickup (required)
        :type supermodel_io_logistics_express_pickup_request: SupermodelIoLogisticsExpressPickupRequest
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_serialize(
            supermodel_io_logistics_express_pickup_request=supermodel_io_logistics_express_pickup_request,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "SupermodelIoLogisticsExpressPickupResponse",
            '400': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def exp_api_pickups_with_http_info(
        self,
        supermodel_io_logistics_express_pickup_request: Annotated[SupermodelIoLogisticsExpressPickupRequest, Field(description="Details about the requested pickup")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SupermodelIoLogisticsExpressPickupResponse]:
        """Create a DHL Express pickup booking request

        The Pickup service creates a DHL Express pickup booking request 

        :param supermodel_io_logistics_express_pickup_request: Details about the requested pickup (required)
        :type supermodel_io_logistics_express_pickup_request: SupermodelIoLogisticsExpressPickupRequest
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_serialize(
            supermodel_io_logistics_express_pickup_request=supermodel_io_logistics_express_pickup_request,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "SupermodelIoLogisticsExpressPickupResponse",
            '400': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def exp_api_pickups_without_preload_content(
        self,
        supermodel_io_logistics_express_pickup_request: Annotated[SupermodelIoLogisticsExpressPickupRequest, Field(description="Details about the requested pickup")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create a DHL Express pickup booking request

        The Pickup service creates a DHL Express pickup booking request 

        :param supermodel_io_logistics_express_pickup_request: Details about the requested pickup (required)
        :type supermodel_io_logistics_express_pickup_request: SupermodelIoLogisticsExpressPickupRequest
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_serialize(
            supermodel_io_logistics_express_pickup_request=supermodel_io_logistics_express_pickup_request,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "SupermodelIoLogisticsExpressPickupResponse",
            '400': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _exp_api_pickups_serialize(
        self,
        supermodel_io_logistics_express_pickup_request,
        message_reference,
        message_reference_date,
        plugin_name,
        plugin_version,
        shipping_system_platform_name,
        shipping_system_platform_version,
        webstore_platform_name,
        webstore_platform_version,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if message_reference is not None:
            _header_params['Message-Reference'] = message_reference
        if message_reference_date is not None:
            _header_params['Message-Reference-Date'] = message_reference_date
        if plugin_name is not None:
            _header_params['Plugin-Name'] = plugin_name
        if plugin_version is not None:
            _header_params['Plugin-Version'] = plugin_version
        if shipping_system_platform_name is not None:
            _header_params['Shipping-System-Platform-Name'] = shipping_system_platform_name
        if shipping_system_platform_version is not None:
            _header_params['Shipping-System-Platform-Version'] = shipping_system_platform_version
        if webstore_platform_name is not None:
            _header_params['Webstore-Platform-Name'] = webstore_platform_name
        if webstore_platform_version is not None:
            _header_params['Webstore-Platform-Version'] = webstore_platform_version
        # process the form parameters
        # process the body parameter
        if supermodel_io_logistics_express_pickup_request is not None:
            _body_params = supermodel_io_logistics_express_pickup_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/pickups',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def exp_api_pickups_cancel(
        self,
        dispatch_confirmation_number: Annotated[StrictStr, Field(description="Shipment pickup confirmation number for example `PRG999126012345`")],
        requestor_name: Annotated[StrictStr, Field(description="Name of the person requesting to cancel the scheduled pickup ")],
        reason: Annotated[StrictStr, Field(description="Provide why scheduled pickup is being cancelled ")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Cancel a DHL Express pickup booking request

        The Cancel Pickup service can be used to cancel a DHL Express pickup booking request 

        :param dispatch_confirmation_number: Shipment pickup confirmation number for example `PRG999126012345` (required)
        :type dispatch_confirmation_number: str
        :param requestor_name: Name of the person requesting to cancel the scheduled pickup  (required)
        :type requestor_name: str
        :param reason: Provide why scheduled pickup is being cancelled  (required)
        :type reason: str
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_cancel_serialize(
            dispatch_confirmation_number=dispatch_confirmation_number,
            requestor_name=requestor_name,
            reason=reason,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '400': "SupermodelIoLogisticsExpressErrorResponse",
            '404': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def exp_api_pickups_cancel_with_http_info(
        self,
        dispatch_confirmation_number: Annotated[StrictStr, Field(description="Shipment pickup confirmation number for example `PRG999126012345`")],
        requestor_name: Annotated[StrictStr, Field(description="Name of the person requesting to cancel the scheduled pickup ")],
        reason: Annotated[StrictStr, Field(description="Provide why scheduled pickup is being cancelled ")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Cancel a DHL Express pickup booking request

        The Cancel Pickup service can be used to cancel a DHL Express pickup booking request 

        :param dispatch_confirmation_number: Shipment pickup confirmation number for example `PRG999126012345` (required)
        :type dispatch_confirmation_number: str
        :param requestor_name: Name of the person requesting to cancel the scheduled pickup  (required)
        :type requestor_name: str
        :param reason: Provide why scheduled pickup is being cancelled  (required)
        :type reason: str
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_cancel_serialize(
            dispatch_confirmation_number=dispatch_confirmation_number,
            requestor_name=requestor_name,
            reason=reason,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '400': "SupermodelIoLogisticsExpressErrorResponse",
            '404': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def exp_api_pickups_cancel_without_preload_content(
        self,
        dispatch_confirmation_number: Annotated[StrictStr, Field(description="Shipment pickup confirmation number for example `PRG999126012345`")],
        requestor_name: Annotated[StrictStr, Field(description="Name of the person requesting to cancel the scheduled pickup ")],
        reason: Annotated[StrictStr, Field(description="Provide why scheduled pickup is being cancelled ")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Cancel a DHL Express pickup booking request

        The Cancel Pickup service can be used to cancel a DHL Express pickup booking request 

        :param dispatch_confirmation_number: Shipment pickup confirmation number for example `PRG999126012345` (required)
        :type dispatch_confirmation_number: str
        :param requestor_name: Name of the person requesting to cancel the scheduled pickup  (required)
        :type requestor_name: str
        :param reason: Provide why scheduled pickup is being cancelled  (required)
        :type reason: str
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_cancel_serialize(
            dispatch_confirmation_number=dispatch_confirmation_number,
            requestor_name=requestor_name,
            reason=reason,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
            '400': "SupermodelIoLogisticsExpressErrorResponse",
            '404': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _exp_api_pickups_cancel_serialize(
        self,
        dispatch_confirmation_number,
        requestor_name,
        reason,
        message_reference,
        message_reference_date,
        plugin_name,
        plugin_version,
        shipping_system_platform_name,
        shipping_system_platform_version,
        webstore_platform_name,
        webstore_platform_version,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if dispatch_confirmation_number is not None:
            _path_params['dispatchConfirmationNumber'] = dispatch_confirmation_number
        # process the query parameters
        if requestor_name is not None:
            
            _query_params.append(('requestorName', requestor_name))
            
        if reason is not None:
            
            _query_params.append(('reason', reason))
            
        # process the header parameters
        if message_reference is not None:
            _header_params['Message-Reference'] = message_reference
        if message_reference_date is not None:
            _header_params['Message-Reference-Date'] = message_reference_date
        if plugin_name is not None:
            _header_params['Plugin-Name'] = plugin_name
        if plugin_version is not None:
            _header_params['Plugin-Version'] = plugin_version
        if shipping_system_platform_name is not None:
            _header_params['Shipping-System-Platform-Name'] = shipping_system_platform_name
        if shipping_system_platform_version is not None:
            _header_params['Shipping-System-Platform-Version'] = shipping_system_platform_version
        if webstore_platform_name is not None:
            _header_params['Webstore-Platform-Name'] = webstore_platform_name
        if webstore_platform_version is not None:
            _header_params['Webstore-Platform-Version'] = webstore_platform_version
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/pickups/{dispatchConfirmationNumber}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def exp_api_pickups_update(
        self,
        dispatch_confirmation_number: Annotated[StrictStr, Field(description="Shipment pickup confirmation number for example `PRG999126012345`")],
        supermodel_io_logistics_express_update_pickup_request: Annotated[SupermodelIoLogisticsExpressUpdatePickupRequest, Field(description="Details about the requested pickup updates")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SupermodelIoLogisticsExpressUpdatePickupResponse:
        """Update pickup information for an existing DHL Express pickup booking request

        The Update Pickup service can be used to update pickup information for an existing DHL Express pickup booking request 

        :param dispatch_confirmation_number: Shipment pickup confirmation number for example `PRG999126012345` (required)
        :type dispatch_confirmation_number: str
        :param supermodel_io_logistics_express_update_pickup_request: Details about the requested pickup updates (required)
        :type supermodel_io_logistics_express_update_pickup_request: SupermodelIoLogisticsExpressUpdatePickupRequest
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_update_serialize(
            dispatch_confirmation_number=dispatch_confirmation_number,
            supermodel_io_logistics_express_update_pickup_request=supermodel_io_logistics_express_update_pickup_request,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SupermodelIoLogisticsExpressUpdatePickupResponse",
            '400': "SupermodelIoLogisticsExpressErrorResponse",
            '404': "SupermodelIoLogisticsExpressErrorResponse",
            '422': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def exp_api_pickups_update_with_http_info(
        self,
        dispatch_confirmation_number: Annotated[StrictStr, Field(description="Shipment pickup confirmation number for example `PRG999126012345`")],
        supermodel_io_logistics_express_update_pickup_request: Annotated[SupermodelIoLogisticsExpressUpdatePickupRequest, Field(description="Details about the requested pickup updates")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SupermodelIoLogisticsExpressUpdatePickupResponse]:
        """Update pickup information for an existing DHL Express pickup booking request

        The Update Pickup service can be used to update pickup information for an existing DHL Express pickup booking request 

        :param dispatch_confirmation_number: Shipment pickup confirmation number for example `PRG999126012345` (required)
        :type dispatch_confirmation_number: str
        :param supermodel_io_logistics_express_update_pickup_request: Details about the requested pickup updates (required)
        :type supermodel_io_logistics_express_update_pickup_request: SupermodelIoLogisticsExpressUpdatePickupRequest
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_update_serialize(
            dispatch_confirmation_number=dispatch_confirmation_number,
            supermodel_io_logistics_express_update_pickup_request=supermodel_io_logistics_express_update_pickup_request,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SupermodelIoLogisticsExpressUpdatePickupResponse",
            '400': "SupermodelIoLogisticsExpressErrorResponse",
            '404': "SupermodelIoLogisticsExpressErrorResponse",
            '422': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def exp_api_pickups_update_without_preload_content(
        self,
        dispatch_confirmation_number: Annotated[StrictStr, Field(description="Shipment pickup confirmation number for example `PRG999126012345`")],
        supermodel_io_logistics_express_update_pickup_request: Annotated[SupermodelIoLogisticsExpressUpdatePickupRequest, Field(description="Details about the requested pickup updates")],
        message_reference: Annotated[Optional[Annotated[str, Field(min_length=28, strict=True, max_length=36)]], Field(description="Please provide message reference ")] = None,
        message_reference_date: Annotated[Optional[StrictStr], Field(description="Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2")] = None,
        plugin_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the plugin (applicable to 3PV only) ")] = None,
        plugin_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the plugin (applicable to 3PV only) ")] = None,
        shipping_system_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the shipping platform(applicable to 3PV only) ")] = None,
        shipping_system_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the shipping platform (applicable to 3PV only) ")] = None,
        webstore_platform_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Please provide name of the webstore platform (applicable to 3PV only) ")] = None,
        webstore_platform_version: Annotated[Optional[Annotated[str, Field(strict=True, max_length=15)]], Field(description="Please provide version of the webstore platform (applicable to 3PV only) ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update pickup information for an existing DHL Express pickup booking request

        The Update Pickup service can be used to update pickup information for an existing DHL Express pickup booking request 

        :param dispatch_confirmation_number: Shipment pickup confirmation number for example `PRG999126012345` (required)
        :type dispatch_confirmation_number: str
        :param supermodel_io_logistics_express_update_pickup_request: Details about the requested pickup updates (required)
        :type supermodel_io_logistics_express_update_pickup_request: SupermodelIoLogisticsExpressUpdatePickupRequest
        :param message_reference: Please provide message reference 
        :type message_reference: str
        :param message_reference_date: Optional reference date in the  HTTP-date format https://tools.ietf.org/html/rfc7231#section-7.1.1.2
        :type message_reference_date: str
        :param plugin_name: Please provide name of the plugin (applicable to 3PV only) 
        :type plugin_name: str
        :param plugin_version: Please provide version of the plugin (applicable to 3PV only) 
        :type plugin_version: str
        :param shipping_system_platform_name: Please provide name of the shipping platform(applicable to 3PV only) 
        :type shipping_system_platform_name: str
        :param shipping_system_platform_version: Please provide version of the shipping platform (applicable to 3PV only) 
        :type shipping_system_platform_version: str
        :param webstore_platform_name: Please provide name of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_name: str
        :param webstore_platform_version: Please provide version of the webstore platform (applicable to 3PV only) 
        :type webstore_platform_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._exp_api_pickups_update_serialize(
            dispatch_confirmation_number=dispatch_confirmation_number,
            supermodel_io_logistics_express_update_pickup_request=supermodel_io_logistics_express_update_pickup_request,
            message_reference=message_reference,
            message_reference_date=message_reference_date,
            plugin_name=plugin_name,
            plugin_version=plugin_version,
            shipping_system_platform_name=shipping_system_platform_name,
            shipping_system_platform_version=shipping_system_platform_version,
            webstore_platform_name=webstore_platform_name,
            webstore_platform_version=webstore_platform_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SupermodelIoLogisticsExpressUpdatePickupResponse",
            '400': "SupermodelIoLogisticsExpressErrorResponse",
            '404': "SupermodelIoLogisticsExpressErrorResponse",
            '422': "SupermodelIoLogisticsExpressErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _exp_api_pickups_update_serialize(
        self,
        dispatch_confirmation_number,
        supermodel_io_logistics_express_update_pickup_request,
        message_reference,
        message_reference_date,
        plugin_name,
        plugin_version,
        shipping_system_platform_name,
        shipping_system_platform_version,
        webstore_platform_name,
        webstore_platform_version,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if dispatch_confirmation_number is not None:
            _path_params['dispatchConfirmationNumber'] = dispatch_confirmation_number
        # process the query parameters
        # process the header parameters
        if message_reference is not None:
            _header_params['Message-Reference'] = message_reference
        if message_reference_date is not None:
            _header_params['Message-Reference-Date'] = message_reference_date
        if plugin_name is not None:
            _header_params['Plugin-Name'] = plugin_name
        if plugin_version is not None:
            _header_params['Plugin-Version'] = plugin_version
        if shipping_system_platform_name is not None:
            _header_params['Shipping-System-Platform-Name'] = shipping_system_platform_name
        if shipping_system_platform_version is not None:
            _header_params['Shipping-System-Platform-Version'] = shipping_system_platform_version
        if webstore_platform_name is not None:
            _header_params['Webstore-Platform-Name'] = webstore_platform_name
        if webstore_platform_version is not None:
            _header_params['Webstore-Platform-Version'] = webstore_platform_version
        # process the form parameters
        # process the body parameter
        if supermodel_io_logistics_express_update_pickup_request is not None:
            _body_params = supermodel_io_logistics_express_update_pickup_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/pickups/{dispatchConfirmationNumber}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


