# Generated by Django 4.2.3 on 2023-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('sitecol', models.CharField(blank=True, max_length=45, null=True)),
                ('lat', models.CharField(blank=True, max_length=45, null=True)),
                ('long', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'site',
                'ordering': ('site_name',),
                'managed': True,
            },
        ),
    ]
